# Generated by Django 5.0 on 2024-01-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("genre_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MPAARating",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_path", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                ("language", models.CharField(max_length=50)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Moderate"),
                            (4, "High"),
                            (5, "Very High"),
                        ]
                    ),
                ),
                ("genre", models.ManyToManyField(to="movies.genre")),
            ],
        ),
        migrations.CreateModel(
            name="MPARatingMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpaa_ratings",
                        to="movies.movie",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="movies.mpaarating",
                    ),
                ),
            ],
            options={
                "unique_together": {("rating", "movie")},
            },
        ),
    ]
