# Generated by Django 5.0 on 2024-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre_name",
            new_name="genreName",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="image_path",
            new_name="imgPath",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="rating",
            new_name="userRating",
        ),
        migrations.RenameField(
            model_name="mpaarating",
            old_name="rating_type",
            new_name="ratingType",
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
